# appspec.yml

version: 0.0

# Deploy 대상 서버의 운영체제를 표시
os: linux

files:
  # 코드 파일의 소스 경로
  - source: /
    # 코드 파일의 대상 경로 -> /home/ec2-user/app 디렉토리로 파일을 복사한다.
    destination: /home/ec2-user/app # 프로젝트 이름
    # 대상 경로에 이미 파일이 존재하는 경우, 덮어쓰기를 허용할지 여부
    overwrite: yes

# 파일 및 디렉토리 권한에 관련된 설정
permissions:
  # 권한을 설정할 대상 경로
  - object: /
    # 모든 파일 및 디렉토리를 의미
    pattern: "**"
    # 파일 및 디렉토리의 소유자를 ec2-user로 설정
    owner: ec2-user
    # 파일 및 디렉토리의 그룹을 ec2-user로 설정
    group: ec2-user

# Deploy 전후에 실행할 스크립트 또는 명령에 관련된 설정
hooks:
  # 애플리케이션 시작시 실행할 스크립트 또는 명령에 관련된 설정
  AfterInstall:
    - location: scripts/stop.sh # Nginx와 연결되어 있지 않은 스프링부트를 종료한다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh # Nginx와 연결되어 있지 않은 Port로 새 버전의 스프링부트를 시작한다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인한다.
      timeout: 60
      runas: ec2-user
